import React from 'react';
import { IntentType, IntentConfig, TargetLanguage, ThemeConfig } from './types';
import { 
  Heart, 
  Wrench, 
  LifeBuoy, 
  Lightbulb, 
  Wind, 
  Trophy, 
  Users,
  Feather,
  Smile,
  ShieldCheck,
  Zap,
  MoreHorizontal
} from 'lucide-react';

export const INTENTS: IntentConfig[] = [
  {
    type: IntentType.CONFESS,
    label: "Confess",
    icon: "Heart",
    color: "bg-pink-500",
    description: "Share feelings safely."
  },
  {
    type: IntentType.REPAIR,
    label: "Repair",
    icon: "Wrench",
    color: "bg-blue-500",
    description: "Fix a friendship."
  },
  {
    type: IntentType.HELP,
    label: "Seek Help",
    icon: "LifeBuoy",
    color: "bg-orange-500",
    description: "Ask for support."
  },
  {
    type: IntentType.SUGGEST,
    label: "Suggest",
    icon: "Lightbulb",
    color: "bg-yellow-500",
    description: "Constructive feedback."
  },
  {
    type: IntentType.VENT,
    label: "Vent",
    icon: "Wind",
    color: "bg-gray-500",
    description: "Let it out safely."
  },
  {
    type: IntentType.APPRECIATION,
    label: "Thanks",
    icon: "Trophy",
    color: "bg-green-500",
    description: "Show gratitude."
  },
  {
    type: IntentType.FRIENDSHIP,
    label: "Connect",
    icon: "Users",
    color: "bg-indigo-500",
    description: "Find teammates/friends."
  },
  {
    type: IntentType.OTHERS,
    label: "Others",
    icon: "MoreHorizontal",
    color: "bg-slate-500",
    description: "Something else."
  }
];

export const LANGUAGES: { value: TargetLanguage; label: string; flag: string }[] = [
  { value: 'English', label: 'English', flag: '🇺🇸' },
  { value: 'Chinese', label: '中文', flag: '🇨🇳' },
  { value: 'Korean', label: '한국어', flag: '🇰🇷' },
  { value: 'Japanese', label: '日本語', flag: '🇯🇵' },
];

export const THEMES: ThemeConfig[] = [
  { id: 'Dark', label: 'Midnight', bgClass: 'bg-slate-900', textClass: 'text-white', cardClass: 'bg-white/10 border-white/20', accentColor: '#2DD4BF', font: 'font-sans' },
  { id: 'Light', label: 'Daylight', bgClass: 'bg-slate-50', textClass: 'text-slate-900', cardClass: 'bg-white/60 border-black/5 shadow-lg', accentColor: '#FB7185', font: 'font-sans' },
  { id: 'Code', label: 'Terminal', bgClass: 'bg-[#0d1117]', textClass: 'text-[#c9d1d9]', cardClass: 'bg-[#161b22] border-[#30363d]', accentColor: '#58a6ff', font: 'font-mono', hideBlobs: true },
  { id: 'Word', label: 'Paper', bgClass: 'bg-[#f3f2f1]', textClass: 'text-[#201f1e]', cardClass: 'bg-white border-black/10 shadow-sm', accentColor: '#2b579a', font: 'font-serif', hideBlobs: true },
  { id: 'Excel', label: 'Grid', bgClass: 'bg-white', textClass: 'text-[#201f1e]', cardClass: 'bg-white border-[#217346]/20 shadow-sm', accentColor: '#217346', font: 'font-sans', hideBlobs: true },
  { id: 'PowerPoint', label: 'Presentation', bgClass: 'bg-[#f3f2f1]', textClass: 'text-[#201f1e]', cardClass: 'bg-white border-[#b7472a]/20 shadow-sm', accentColor: '#b7472a', font: 'font-sans', hideBlobs: true },
  { id: 'WeChat', label: 'Messenger', bgClass: 'bg-[#f5f5f5]', textClass: 'text-black', cardClass: 'bg-white border-black/5', accentColor: '#07c160', font: 'font-sans', hideBlobs: true },
  { id: 'X', label: 'Void', bgClass: 'bg-black', textClass: 'text-white', cardClass: 'bg-black border-white/20', accentColor: '#1d9bf0', font: 'font-sans', hideBlobs: true },
];

export const TRANSLATIONS: Record<TargetLanguage, Record<string, string>> = {
  'English': {
    'hero.title': 'WhisperWall',
    'hero.subtitle': 'Express yourself safely. Connect deeply.\nAn anonymous space for kindness and truth.',
    'hero.start': 'Start Whispering',
    'intent.title': "What's on your mind?",
    'intent.subtitle': 'Select an intention to guide your expression.',
    'drafting.targetLanguage': 'Target Language',
    'drafting.recipient': 'To Whom?',
    'drafting.recipientPlaceholder': 'e.g., Lab Partner, Roommate',
    'drafting.relationship': 'Relationship',
    'drafting.relationshipPlaceholder': 'e.g., Close friend, Acquaintance',
    'drafting.context': 'Context',
    'drafting.contextPlaceholder': 'Describe the situation honestly. How do you feel?',
    'drafting.save': 'Save Draft',
    'drafting.saved': 'Saved',
    'drafting.load': 'Load Draft',
    'drafting.generate': 'Generate',
    'generation.loading': 'Calibrating Tone...',
    'generation.subtitle': 'Checking for emotional safety',
    'generation.choose': 'Choose Your Voice',
    'generation.chooseSubtitle': 'Select the version that feels most authentic.',
    'generation.safetyNote': 'AI Note',
    'generation.select': 'Select Version',
    'dashboard.ready': 'Ready to Send',
    'dashboard.intentDetected': 'Intent Detected',
    'dashboard.formatting': 'Formatting...',
    'dashboard.addingEmojis': 'Emojis...',
    'dashboard.email': 'Email',
    'dashboard.sms': 'SMS',
    'dashboard.public': 'Public Wall?',
    'dashboard.publicDesc': 'Post anonymously.',
    'dashboard.post': 'Post',
    'dashboard.posted': 'Posted',
    'dashboard.link': 'Anonymous Link',
    'dashboard.linkDesc': 'Recipient views in a safe UI.',
    'dashboard.quests': 'Quests',
    'dashboard.bond': 'Bond',
    'dashboard.topics': 'Topics',
    'dashboard.reset': 'New Whisper',
    'wall.title': 'Campus Whispers',
    'wall.subtitle': 'A safe space to read what others are feeling. You are not alone.',
    'wall.write': 'Share a Whisper',
    'wall.empty': 'No whispers yet. Be the first.',
    'settings.theme': 'Theme',
    'settings.language': 'Language',
    'encrypt.title': 'Encrypt',
    'encrypt.restore': 'Restore',
    'encrypt.base64': 'Base64',
    'encrypt.rot13': 'ROT13',
    'encrypt.reverse': 'Reverse',
    'wall.filter.all': 'All',
    'wall.filter.vents': 'Venting',
    'wall.viewOriginal': 'Original',
    'wall.viewPolished': 'Polished',
    'wall.originalWarning': 'Original',
  },
  'Chinese': {
    'hero.title': '悄悄墙',
    'hero.subtitle': '安全表达，深度连接。\n一个充满善意与真诚的匿名空间。',
    'hero.start': '开始倾诉',
    'intent.title': '你想说什么？',
    'intent.subtitle': '选择一个意图来引导你的表达。',
    'drafting.targetLanguage': '目标语言',
    'drafting.recipient': '发给谁？',
    'drafting.recipientPlaceholder': '例如：实验搭档，室友',
    'drafting.relationship': '关系',
    'drafting.relationshipPlaceholder': '例如：好友，点头之交',
    'drafting.context': '背景',
    'drafting.contextPlaceholder': '诚实地描述情况。你感觉如何？',
    'drafting.save': '保存草稿',
    'drafting.saved': '已保存',
    'drafting.load': '加载',
    'drafting.generate': '生成表达',
    'generation.loading': '正在校准语气...',
    'generation.subtitle': '进行情感安全检查',
    'generation.choose': '选择语调',
    'generation.chooseSubtitle': '选择最符合你心声的版本。',
    'generation.safetyNote': 'AI 提示',
    'generation.select': '选择此版',
    'dashboard.ready': '准备发送',
    'dashboard.intentDetected': '意图',
    'dashboard.formatting': '格式化...',
    'dashboard.addingEmojis': '加表情...',
    'dashboard.email': '邮件',
    'dashboard.sms': '短信',
    'dashboard.public': '公开展示？',
    'dashboard.publicDesc': '匿名发布到墙上。',
    'dashboard.post': '发布',
    'dashboard.posted': '已发布',
    'dashboard.link': '匿名链接',
    'dashboard.linkDesc': '接收者将在安全界面查看。',
    'dashboard.quests': '连接任务',
    'dashboard.bond': '关系',
    'dashboard.topics': '话题',
    'dashboard.reset': '再写一条',
    'wall.title': '校园悄悄话',
    'wall.subtitle': '阅读他人的感受，你并不孤单。',
    'wall.write': '分享心声',
    'wall.empty': '暂无悄悄话。',
    'settings.theme': '主题',
    'settings.language': '语言',
    'encrypt.title': '加密',
    'encrypt.restore': '还原',
    'encrypt.base64': 'Base64',
    'encrypt.rot13': 'ROT13',
    'encrypt.reverse': '反转',
    'wall.filter.all': '全部',
    'wall.filter.vents': '吐槽',
    'wall.viewOriginal': '原文',
    'wall.viewPolished': '美化',
    'wall.originalWarning': '原文',
  },
  'Korean': {
    'hero.title': '위스퍼월',
    'hero.subtitle': '안전하게 표현하고, 깊게 연결하세요.\n친절과 진실을 위한 익명 공간입니다.',
    'hero.start': '시작하기',
    'intent.title': '어떤 마음인가요?',
    'intent.subtitle': '당신의 표현을 도울 의도를 선택하세요.',
    'drafting.targetLanguage': '언어 선택',
    'drafting.recipient': '누구에게?',
    'drafting.recipientPlaceholder': '예: 룸메이트, 지민',
    'drafting.relationship': '관계',
    'drafting.relationshipPlaceholder': '예: 절친, 아는 사이',
    'drafting.context': '상황',
    'drafting.contextPlaceholder': '상황을 묘사하세요. 어떤 기분인가요?',
    'drafting.save': '저장',
    'drafting.saved': '저장됨',
    'drafting.load': '불러오기',
    'drafting.generate': '생성하기',
    'generation.loading': '톤 조절 중...',
    'generation.subtitle': '안전 점검 중',
    'generation.choose': '목소리 선택',
    'generation.chooseSubtitle': '가장 진심에 가까운 버전을 선택하세요.',
    'generation.safetyNote': 'AI 노트',
    'generation.select': '선택하기',
    'dashboard.ready': '전송 준비',
    'dashboard.intentDetected': '의도',
    'dashboard.formatting': '서식...',
    'dashboard.addingEmojis': '이모지...',
    'dashboard.email': '이메일',
    'dashboard.sms': '문자',
    'dashboard.public': '공개?',
    'dashboard.publicDesc': '익명으로 게시합니다.',
    'dashboard.post': '게시',
    'dashboard.posted': '게시됨',
    'dashboard.link': '익명 링크',
    'dashboard.linkDesc': '수신자는 안전한 UI에서 봅니다.',
    'dashboard.quests': '퀘스트',
    'dashboard.bond': '유대감',
    'dashboard.topics': '대화 주제',
    'dashboard.reset': '새로 쓰기',
    'wall.title': '캠퍼스 속삭임',
    'wall.subtitle': '타인의 마음을 읽는 안전한 공간.',
    'wall.write': '이야기 공유',
    'wall.empty': '아직 글이 없습니다.',
    'settings.theme': '테마',
    'settings.language': '언어',
    'encrypt.title': '암호화',
    'encrypt.restore': '복원',
    'encrypt.base64': 'Base64',
    'encrypt.rot13': 'ROT13',
    'encrypt.reverse': '반전',
    'wall.filter.all': '전체',
    'wall.filter.vents': '대나무숲',
    'wall.viewOriginal': '원본',
    'wall.viewPolished': '순화됨',
    'wall.originalWarning': '원본',
  },
  'Japanese': {
    'hero.title': 'WhisperWall',
    'hero.subtitle': '安全に表現し、深くつながる。\n優しさと真実のための匿名空間。',
    'hero.start': '始める',
    'intent.title': '何を考えていますか？',
    'intent.subtitle': '表現したい意図を選んでください。',
    'drafting.targetLanguage': '言語',
    'drafting.recipient': '誰に？',
    'drafting.recipientPlaceholder': '例：ルームメイト、佐藤さん',
    'drafting.relationship': '関係',
    'drafting.relationshipPlaceholder': '例：親友、知人',
    'drafting.context': '文脈',
    'drafting.contextPlaceholder': '状況を説明してください。どう感じていますか？',
    'drafting.save': '保存',
    'drafting.saved': '保存済',
    'drafting.load': '読込',
    'drafting.generate': '生成',
    'generation.loading': '調整中...',
    'generation.subtitle': '安全性を確認中',
    'generation.choose': '声を選ぶ',
    'generation.chooseSubtitle': '最も自分らしいものを選んでください。',
    'generation.safetyNote': 'AI メモ',
    'generation.select': '選択',
    'dashboard.ready': '送信準備',
    'dashboard.intentDetected': '意図',
    'dashboard.formatting': '整形中...',
    'dashboard.addingEmojis': '絵文字...',
    'dashboard.email': 'メール',
    'dashboard.sms': 'SMS',
    'dashboard.public': '公開？',
    'dashboard.publicDesc': '匿名で投稿します。',
    'dashboard.post': '投稿',
    'dashboard.posted': '投稿完',
    'dashboard.link': '匿名リンク',
    'dashboard.linkDesc': '安全なUIで表示されます。',
    'dashboard.quests': 'クエスト',
    'dashboard.bond': '絆',
    'dashboard.topics': '話題',
    'dashboard.reset': '新規作成',
    'wall.title': 'キャンパスの囁き',
    'wall.subtitle': '他人の気持ちを読める安全な場所。',
    'wall.write': '投稿する',
    'wall.empty': 'まだ投稿がありません。',
    'settings.theme': 'テーマ',
    'settings.language': '言語',
    'encrypt.title': '暗号化',
    'encrypt.restore': '戻す',
    'encrypt.base64': 'Base64',
    'encrypt.rot13': 'ROT13',
    'encrypt.reverse': '反転',
    'wall.filter.all': 'すべて',
    'wall.filter.vents': '不満',
    'wall.viewOriginal': '原文',
    'wall.viewPolished': '修正版',
    'wall.originalWarning': '原文',
  }
};

export const getIcon = (name: string, size: number = 24) => {
  const props = { size, className: "text-current opacity-90" };
  switch (name) {
    case 'Heart': return <Heart {...props} />;
    case 'Wrench': return <Wrench {...props} />;
    case 'LifeBuoy': return <LifeBuoy {...props} />;
    case 'Lightbulb': return <Lightbulb {...props} />;
    case 'Wind': return <Wind {...props} />;
    case 'Trophy': return <Trophy {...props} />;
    case 'Users': return <Users {...props} />;
    case 'Feather': return <Feather {...props} />;
    case 'Smile': return <Smile {...props} />;
    case 'ShieldCheck': return <ShieldCheck {...props} />;
    case 'Zap': return <Zap {...props} />;
    case 'MoreHorizontal': return <MoreHorizontal {...props} />;
    default: return <Feather {...props} />;
  }
};